# example
stages:
  - name: Build something
    steps:
    - runScriptConfig:
        image: busybox
        shellScript: echo "oi"
        shellScript: pwd
  - name: Deploy some workloads
    steps:
    - applyYamlConfig:
        path: ./kubernetes/backend.yml