# example
stages:
  - name: Build something
    steps:
    - runScriptConfig:
        shellScript: echo "ois"
  - name: Deploy some workloads
    steps:
    - applyYamlConfig:
        path: ./kubernetes/backend.yml